version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/blog_db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: