version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_test_db
    environment:
      POSTGRES_DB: test_blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_blog"]
      interval: 5s
      timeout: 5s
      retries: 10

  tests:
    build:
      context: .
      dockerfile: dockerfile.tests
    container_name: fastapi_tests
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/test_blog
    volumes:
      - .:/app
    command: uv run pytest tests/ -V

volumes:
  postgres_data: